version: '3.8'

services:
  backend:
    image: arfudy-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: ${DATABASE_URL}
